// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.21.12
// source: internal/proto/thumbnail.proto

package thumbnail

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetThumbnailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThumbnailRequest) Reset() {
	*x = GetThumbnailRequest{}
	mi := &file_internal_proto_thumbnail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThumbnailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailRequest) ProtoMessage() {}

func (x *GetThumbnailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_thumbnail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailRequest.ProtoReflect.Descriptor instead.
func (*GetThumbnailRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_thumbnail_proto_rawDescGZIP(), []int{0}
}

func (x *GetThumbnailRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetThumbnailsRequestAsync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThumbnailsRequestAsync) Reset() {
	*x = GetThumbnailsRequestAsync{}
	mi := &file_internal_proto_thumbnail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThumbnailsRequestAsync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThumbnailsRequestAsync) ProtoMessage() {}

func (x *GetThumbnailsRequestAsync) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_thumbnail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThumbnailsRequestAsync.ProtoReflect.Descriptor instead.
func (*GetThumbnailsRequestAsync) Descriptor() ([]byte, []int) {
	return file_internal_proto_thumbnail_proto_rawDescGZIP(), []int{1}
}

func (x *GetThumbnailsRequestAsync) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

type ThumbnailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Thumbnail     []byte                 `protobuf:"bytes,2,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThumbnailResponse) Reset() {
	*x = ThumbnailResponse{}
	mi := &file_internal_proto_thumbnail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThumbnailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThumbnailResponse) ProtoMessage() {}

func (x *ThumbnailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_thumbnail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThumbnailResponse.ProtoReflect.Descriptor instead.
func (*ThumbnailResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_thumbnail_proto_rawDescGZIP(), []int{2}
}

func (x *ThumbnailResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ThumbnailResponse) GetThumbnail() []byte {
	if x != nil {
		return x.Thumbnail
	}
	return nil
}

func (x *ThumbnailResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_proto_thumbnail_proto protoreflect.FileDescriptor

var file_internal_proto_thumbnail_proto_rawDesc = string([]byte{
	0x0a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x74, 0x68, 0x75, 0x6d, 0x6e, 0x61, 0x69, 0x6c, 0x22, 0x27, 0x0a, 0x13, 0x47, 0x65,
	0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x72, 0x6c, 0x22, 0x2f, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e,
	0x61, 0x69, 0x6c, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x73, 0x79, 0x6e, 0x63,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x72, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x75, 0x72, 0x6c, 0x73, 0x22, 0x59, 0x0a, 0x11, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x32,
	0xb7, 0x01, 0x0a, 0x10, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4a, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62,
	0x6e, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x6e, 0x61, 0x69, 0x6c, 0x2e,
	0x47, 0x65, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x6e, 0x61, 0x69, 0x6c, 0x2e, 0x54,
	0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x57, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c,
	0x41, 0x73, 0x79, 0x6e, 0x63, 0x12, 0x23, 0x2e, 0x74, 0x68, 0x75, 0x6d, 0x6e, 0x61, 0x69, 0x6c,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x1a, 0x1b, 0x2e, 0x74, 0x68, 0x75,
	0x6d, 0x6e, 0x61, 0x69, 0x6c, 0x2e, 0x54, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x40, 0x5a, 0x3e, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6c, 0x69, 0x6b, 0x65, 0x73, 0x65, 0x6e, 0x73, 0x65, 0x2f, 0x79, 0x74, 0x5f, 0x74,
	0x65, 0x73, 0x74, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x65, 0x6e, 0x63, 0x65, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72,
	0x74, 0x2f, 0x74, 0x68, 0x75, 0x6d, 0x62, 0x6e, 0x61, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
})

var (
	file_internal_proto_thumbnail_proto_rawDescOnce sync.Once
	file_internal_proto_thumbnail_proto_rawDescData []byte
)

func file_internal_proto_thumbnail_proto_rawDescGZIP() []byte {
	file_internal_proto_thumbnail_proto_rawDescOnce.Do(func() {
		file_internal_proto_thumbnail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_thumbnail_proto_rawDesc), len(file_internal_proto_thumbnail_proto_rawDesc)))
	})
	return file_internal_proto_thumbnail_proto_rawDescData
}

var file_internal_proto_thumbnail_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_internal_proto_thumbnail_proto_goTypes = []any{
	(*GetThumbnailRequest)(nil),       // 0: thumnail.GetThumbnailRequest
	(*GetThumbnailsRequestAsync)(nil), // 1: thumnail.GetThumbnailsRequestAsync
	(*ThumbnailResponse)(nil),         // 2: thumnail.ThumbnailResponse
}
var file_internal_proto_thumbnail_proto_depIdxs = []int32{
	0, // 0: thumnail.ThumbnailService.GetThumbnail:input_type -> thumnail.GetThumbnailRequest
	1, // 1: thumnail.ThumbnailService.GetThumbnailAsync:input_type -> thumnail.GetThumbnailsRequestAsync
	2, // 2: thumnail.ThumbnailService.GetThumbnail:output_type -> thumnail.ThumbnailResponse
	2, // 3: thumnail.ThumbnailService.GetThumbnailAsync:output_type -> thumnail.ThumbnailResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_thumbnail_proto_init() }
func file_internal_proto_thumbnail_proto_init() {
	if File_internal_proto_thumbnail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_thumbnail_proto_rawDesc), len(file_internal_proto_thumbnail_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_thumbnail_proto_goTypes,
		DependencyIndexes: file_internal_proto_thumbnail_proto_depIdxs,
		MessageInfos:      file_internal_proto_thumbnail_proto_msgTypes,
	}.Build()
	File_internal_proto_thumbnail_proto = out.File
	file_internal_proto_thumbnail_proto_goTypes = nil
	file_internal_proto_thumbnail_proto_depIdxs = nil
}
